MYSQL_USER = 'root'
MYSQL_PASSWORD = 'password'
MYSQL_HOST = 'db'
MYSQL_DB = 'rental_data'

SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DB}"
SQLALCHEMY_TRACK_MODIFICATIONS = False